### ISSUE TITLE
Add a template for Drupal 7 projects

### ISSUE THREAD

**Issue by tormi** [wunderio/drupal-project#17]
Add a template for Drupal 7 projects based on https://github.com/drupal-composer/drupal-project/tree/7.x.

**Comment by floretan** [comment]
We won't be starting new Drupal 7 projects, but we need an example for existing projects. Since our existing Drupal 7 projects are almost all based on WunderTools, we should set up the D7 branch of that repository to use composer and deploy to Silta.

**Comment by tormi** [comment]
I'm experimenting with the idea here: https://github.com/tormi/drupal-project
