### ISSUE TITLE
Remove unnecessary gitignore /drush/Commands/

### ISSUE THREAD

**Issue by kirkkala** [wunderio/drupal-project#187]
Is there any reason for the existence of `/drush/Commands/` in [.gitignore](https://github.com/wunderio/drupal-project/blob/b80e1a6/.gitignore#L4)?

Project already has [drush/Commands/PolicyCommands.php](https://github.com/wunderio/drupal-project/blob/master/drush/Commands/PolicyCommands.php) versioned.

**Comment by tormi** [comment]
Thanks, Timo!
