### ISSUE TITLE
Node 12 has been deprecated

### ISSUE THREAD

**Issue by mikaelkundert** [wunderio/drupal-project#275]
Our `lando start` complains about deprecated Node 12 version. We should upgrade to 14 or 16.

I'm not sure what Node version we use in Drupal helm chart.

```
node version 12 is a legacy version! We recommend upgrading.
```

**Comment by kirkkala** [comment]
Should be there already via b860612.

**Comment by mikaelkundert** [comment]
Right, I was having locally `master` branch. That explains...
