### ISSUE TITLE
Set lando timezone to Europe/Helsinki

### ISSUE THREAD

**Issue by misterjoonas** [wunderio/drupal-project#353]
Lando seems to be using UTC as the default timezone.
```
❯ lando ssh
www-data@731ba918ed14:/app$ date
Tue Apr  4 10:43:08 UTC 2023
```
Maybe it should be Europe/Helsinki?
https://docs.lando.dev/guides/how-do-i-set-the-timezone-of-a-lando-service.html

**Comment by hkirsman** [comment]
We had at some point changed our server timezones in Trimble and they still are same as Helsinki +2. I think the reasoning was similar - maybe or why not? But actually years later I learned that it's common practice to set servers to UTC 0 - it provides a standardized reference point without daylight saving time adjustments, making it easier to manage and compare timestamps across different systems (eg Sumo + Datadog + Drupal etc), regions, and time periods.

I think Lando emulates server so in that sense it too should be at UTC 0. 

@tormi @misterjoonas

**Comment by misterjoonas** [comment]
I don't think the timezone normally matters much for the local environment. But in some cases when you need to do for example some integrations, it might become a problem if the timezone is not correct.
