### ISSUE TITLE
Remove drupal/config_installer in favour of drush si --existing-config

### ISSUE THREAD

**Issue by tormi** [wunderio/drupal-project#36]
From https://www.drupal.org/project/config_installer: _This project is (partially) deprecated as Drupal core 8.6 now supports Installing Drupal from configuration._

Change record: [Installing Drupal from configuration (only certain profiles)](https://www.drupal.org/node/2897299). Caveat: If the profile implements `hook_install()` configuration install is not supported.

Drush 9.4 enhanced its `site:install` command with a new` --existing-config` option in order to support this feature.

**Comment by tormi** [comment]
@floretan ?

**Comment by tormi** [comment]
This can be tested with:
1. `lando drush si minimal`
2. `lando drush cex`
3. `lando drush si --existing-config`

**Comment by vermario** [comment]
So, this would mean that we use the `minimal` installation profile under the hood? It's ok for some cases (backend for decoupled site, for example) but for a "normal" site that's quite a big list of stuff you need to enable manually that you would normally get out of the box.

**Comment by tormi** [comment]
Thanks, @vermario!

I used `minimal` only to test `drush si --existing-config` as a concept. 

> for a "normal" site that's quite a big list of stuff you need to enable manually that you would normally get out of the box

We can create default `wunder/silta` profile which doesn't use `hook_install()`.

**Comment by vermario** [comment]
If that works, it would be a good solution I think!

**Comment by floretan** [comment]
According to https://www.drupal.org/node/2910643, it seems that the installation profile that needs to have no hook_install() is the one selected when installing from configuration (`drush si minimal --existing-config`), not the one that was used when creating the initial configuration.

Installation issues have caused quite some trouble, I wouldn't want to switch before we know that `--existing-config` works better than config_installer in practice, including in some more advanced cases like multilingual websites.

**Comment by tormi** [comment]
Ok, let’s keep this open then and collect implementation experiences before moving forward (if at all).

**Comment by tormi** [comment]
[#2357215 Clean up hook_install() in Standard Install Profile](https://www.drupal.org/project/drupal/issues/2357215) is RTBC.

**Comment by tormi** [comment]
This was implemented in https://github.com/wunderio/drupal-project/commit/ce154a0dab1942254c1f87b521e916edfc0c11ee#diff-b5d0ee8c97c7abd7e3fa29b9a27d1780, closing.

**Comment by MatrixOfDeath** [comment]
What if your project already exist (database, contents created, media etc..) with the drupal/config_installer profile ? Therefore you couldn't be using drush si anymore ?

**Comment by tormi** [comment]
@MatrixOfDeath , then the proper command for config import is `drush cim`. BTW, `config_installer` profile is deprecated and should be replaced with core `minimal` or other profile.

**Comment by MatrixOfDeath** [comment]
Yes agreed, but then my question was how to switch to minimal profile coming from config_installer without using drush si

**Comment by tormi** [comment]
Via https://www.drupal.org/project/profile_switcher.
