### ISSUE TITLE
Lando: Add frontend tools to local dev. environment

### ISSUE THREAD

**Issue by tormi** [wunderio/drupal-project#40]
Add `lando npm` and `lando yarn` commands and run `yarn` or `npm install` on build step by default. 

Apply this also on the https://github.com/wunderio/WunderTools

**Comment by tormi** [comment]
>  run yarn or npm install on build step by default.

We're using Yarn as a default builder in CircleCI. Which one is preferred in a local env?

**Comment by dcorb** [comment]
Is only about the default, but anyway can be configured / overridden later ? There are some projects using npm (locked versions taken from package-lock.json) and others using yarn (locked versions taken from yarn.lock file)

@floretan might have stats about which one is more popular across wunder

**Comment by dcorb** [comment]
@tormi  Is there a PR associated to this issue? Or should I test in master directly?

**Comment by tormi** [comment]
> but anyway can be configured / overridden later ?

Yes, you can adjust `.lando.yml` afterwards.

**Comment by tormi** [comment]
No, not yet.

**Comment by tormi** [comment]
https://github.com/wunderio/drupal-project/pull/41

**Comment by tormi** [comment]
Based on Wunder's internal poll we selected `npm` as default tool over Yarn.
