### ISSUE TITLE
Committing anything requires a local php on the host machine

### ISSUE THREAD

**Issue by aleksijohansson** [wunderio/drupal-project#88]
It seems that committing anything using this template requires a local php installation on the host machine with the correct extensions so that some code validation can be run on commit. This seems wrong and limiting. There is no mention of this requirement in the README nor in the original drupal-composer/drupal-project documentation. Could this be changed to have no other requirement from the host machine other than Lando?

**Comment by tormi** [comment]
@guncha25, @hkirsman - is that correct? If so, we need to remove / modify this dependency - otherwise it will make the Lando setup kind of pointless.

**Comment by hkirsman** [comment]
Are you referering to iconv extension? @aleksijohansson

**Comment by guncha25** [comment]
I agree with documentation part that should be addresses ASAP.
Other than that...
Well for you to commit it requires **git on host machine**. Git in this case is supplemented with git hooks that require additional checks **by default**. Use the `--no-verify `(`-n`) flag when you commit which bypasses the pre-commit and commit-msg hooks. 
Other than that it probably is possible to create adapter for this case and have a special composer plugin that overrides grupmhp git hooks with custom ones and then redirects these tasks to lando, but at this time there is not enough resources available to do that. 
On OSX this should work out of box and i kinda refuse to think that for Linux devs this is an issue.

**Comment by aleksijohansson** [comment]
@hkirsman unfortunately I did not make a note of the extensions, but there were more than one extension what was missing from the default php installation on Ubuntu. That said, I don't think the extensions are the issue here, but instead the fact that we rely on the host machine to have php at all and the lack of documentation about that requirement. I totally agree with @tormi that there is no need to have composer on the host machine and it would be better and more consistent to use the composer in Lando to avoid any potential issues caused by different composer versions.

Based on all of your suggestions and considering the time available for this I suggest we do the following:

**Comment by aleksijohansson** [comment]
@hkirsman unfortunately I did not make a note of the extensions, but there were more than one extension what was missing from the default php installation on Ubuntu. The missing extensions might have been because after installing php on Ubuntu I would have needed to restart the terminal app to get all the new variables to PATH, because now I can't reproduce the issue any more when I have php installed on Ubuntu.

That said, I don't think the extensions are the issue here, but instead the fact that we rely on the host machine to have php at all and the lack of documentation about that requirement. I totally agree with @tormi that there is no need to have composer on the host machine and it would be better and more consistent to use the composer in Lando to avoid any potential issues caused by different composer versions.

Having `git` in Lando tooling would have been a great idea. It would have even worked on a Windows host:
![image](https://user-images.githubusercontent.com/4112176/70373908-a4410480-18f5-11ea-85e3-4b528589c13b.png)

But based on my testing it can cause issues because you can have a different branch checked out in Lando and on your host:
![image](https://user-images.githubusercontent.com/4112176/70374126-3e09b100-18f8-11ea-960c-df2307c2387a.png)

@guncha25 requiring to use `-n` would limit the possibilities of using git from for example Visual Studio Code where you can't easily add parameters to the git commands.

Based on all of your suggestions and considering the time available for this I suggest that for the time being we just document the following:

- By default, there is a requirement of php (version?) on the host machine (with extensions x, y and z if there are any required)
- How to disable the additional checks that happen on `git commit` on a per project basis if you for some reason don't want to have them because they prevent your workflow

@guncha25 It would be cool to eventually have the git hooks php commands be relayed to Lando instead of running them on the host!

**Comment by hkirsman** [comment]
It's very odd that you have different GIT status in host and in Lando as everything in your project root is linked into Lando. Whatever status GIT is in, it's in .git folder to my knowing. You don't have the .git folder unlinked in .lando.yml:

    excludes:
      - .git

What's your Lando version? **(lando version** command)

@aleksijohansson aleksijohansson

**Comment by aleksijohansson** [comment]
@hkirsman Sorry for the late reply. I have the latest v3.0.0-rc.23, but I did the test I did on a Windows host so there could be some issue (or slowness) with file syncing between the host and containers. I also don't have the .git folder unlinked in `.lando.yml`. I was using the default https://github.com/wunderio/drupal-project for testing. I could test your example .lando.yml from https://github.com/wunderio/code-quality/issues/41 and see if the issue persists and if it's a permanent issue or just slowness.

**Comment by hkirsman** [comment]
I guess you could double check but seems like Windows issue. @tormi you know anything about how Lando works in Windows? Is there some slowness in syncing?

**Comment by aleksijohansson** [comment]
Seems to be a slowness issue with the file syncing on Windows:
![image](https://user-images.githubusercontent.com/4112176/70556935-850ed500-1b8a-11ea-94db-a9de1d516589.png)

**Comment by aleksijohansson** [comment]
I'm not aware of any known issues with Docker for Windows nor Lando on a Windows host. Running Docker on a Windows host is of course (at least until WSL-2) at lot slower than on a linux host, but same principle applies to macOS. I think on macOS they have been putting more effort (like creating a completely new file system just for this) into the files sharing between the host and containers. That said I haven't noticed the file sharing between the Windows host and containers to be so slow that it would cause issues in practice and I don't think that `lando git` slowness is an issue in practice either now that I tested it a bit more.

**Comment by aleksijohansson** [comment]
Using `lando git` to get around the issue of having php on the host as a dependency would limit the possibility to use some IDEs for managing git because some of them even include their own git executable and it's not possible to change it to `lando git` so I would not be happy with `lando git` as the solution.

My suggestion is still that for the time being we just document the following:

- By default, there is a requirement of php (version?) on the host machine (with extensions x, y and z if there are any required)
- How to disable the additional checks that happen on git commit on a per project basis if you for some reason don't want to have them because they prevent your workflow

**Comment by hkirsman** [comment]
What do you think, would link to the Code Quality tool suffice? There we already have **Pre-requisites** section. I'm not sure what extensions you are referring though, there was the case with iconv we fixed in latest version.

https://github.com/wunderio/code-quality

@aleksijohansson

**Comment by aleksijohansson** [comment]
@hkirsman Personally I think it would be polite that it would be clearly stated in this template that php on the host machine is a requirement because not having it prevents committing anything and in the worst case the error message only says that php is not found and does not tell that you can skip the pre-commit checks with `-n`. I didn't see instructions how to disable the checks in https://github.com/wunderio/code-quality so I still argue that those should be added too.

I'm also not familiar enough to know if any specific extensions are needed and that's why I wrote "if there are any required". I also wasn't aware that you did any changes related to the requirement of iconv extension.

**Comment by hkirsman** [comment]
I commtened about iconv above ;)

> Are you referering to iconv extension? In 1.0.5 version of Code Quality tool we added symfony/polyfill-iconv - the same as Drupal has in it's own composer.json. It's slower than native iconv but it's better than error and/or starting to compile php on your computer or finding the extension.

**Comment by aleksijohansson** [comment]
Sorry, I missed that this means the iconv extension is no longer needed.
