### ISSUE TITLE
Should we use drupal/core-recommended instead of drupal/core?

### ISSUE THREAD

**Issue by mitrpaka** [wunderio/drupal-project#94]
@tormi Thanks for providing Drupal 8.8.0 core update.

While browsing through changes and checking related documentation, noticed following:
- Now as we have taken steps towards use of Drupal Composer Project Templates, should we also use drupal/core-recommended package instead of drupal/core package directly as recommended by drupal/recommended-project template?

Readme of drupal/core-recommended package states following in https://github.com/drupal/core-recommended:

> This project is for use with a Composer-managed Drupal site. It is recommended that all Composer-managed Drupal sites use this project.
> 
> **Require this project instead of the drupal/core subtree split in order to guarentee that all of the dependencies from drupal/core will be included in your Drupal site at exactly the same version that was tested with the version of Drupal you are currently using.**
> 
> The consequences of not using this project is that Drupal's dependencies may "float up" to more recent versions than were tested with Drupal when you use Composer to upgrade your Drupal site. Occasionally, new dependency versions introduce bugs in Drupal. While these sorts of errors are usually corrected fairly quickly, it can still be quite disruptive to be one of the first people encountering one of these bugs. Using the recommended dependencies avoids this problem by only using dependency versions that have already been tested with Drupal.

**Comment by tormi** [comment]
[My implementation](https://github.com/wunderio/drupal-project/pull/89) mirrored https://github.com/drupal-composer/drupal-project/pull/522/commits/de716fedd608be8c3e5f64e2ea509beeb007b338 implemented by @greg-1-anderson. Greg, do you see any problems here?
